spring:

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jwt:
    secret-key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_APPLY_REGION}
      auto: false
    stack:
      auto: false

  open-ai:
    url: ${OPEN_AI_URL}
    secret-key: ${OPEN_AI_SECRET_KEY}

notification:
  sender: ${NOTIFICATION_SENDER}

firebase:
  key:
    path: ${FIREBASE_KEY_PATH}