name: Java CI with Gradle

on:
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Create Firebase Key File
        run: echo "${{secrets.FIREBASE_KEY_JSON}}" > src/main/resources/moodwriterFirebaseKey.json

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: clean build --info
        env:
          SPRING_PROFILES_ACTIVE: prod
          S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
          OPEN_AI_URL: ${{secrets.OPEN_AI_URL}}
          OPEN_AI_SECRET_KEY: ${{secrets.OPEN_AI_SECRET_KEY}}
          RABBIT_MQ_HOST: ${{secrets.RABBIT_MQ_HOST}}
          RABBIT_MQ_USERNAME: ${{secrets.RABBIT_MQ_USERNAME}}
          RABBIT_MQ_PASSWORD: ${{secrets.RABBIT_MQ_PASSWORD}}
          MYSQL_URL: ${{secrets.MYSQL_URL}}
          MYSQL_USERNAME: ${{secrets.MYSQL_USERNAME}}
          MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
          REDIS_HOST: ${{secrets.REDIS_HOST}}
          NOTIFICATION_SENDER: ${{secrets.NOTIFICATION_SENDER}}